version: 2.1

orbs:
  rebar3: tsloughter/rebar3

jobs:
  proper:
    executor: rebar3/erlang
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/
      - run:
          command: |
              rebar3 proper --regressions
              rebar3 proper -c
      # for cover
      - persist_to_workspace:
          root: ~/project/
          paths:
            - _build/test/

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - rebar3/compile
      - rebar3/lint:
          requires:
              - rebar3/compile
      - rebar3/xref:
          requires:
              - rebar3/compile
      - rebar3/dialyzer:
          requires:
              - rebar3/compile
      - rebar3/ct:
          requires:
              - rebar3/compile
      - proper:
          requires:
              - rebar3/compile
              - rebar3/ct # to make cover work, can't be concurrent
      - rebar3/cover:
          requires:
              - rebar3/ct
              - proper
