name: Erlang CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  # Allow unicode output and enable features such as the maybe expression
  ERL_AFLAGS: +pc unicode -enable-feature all
  # github actions does not have a shared filesystem between
  # working files, the /tmp directory, or the ~/.cache directory
  REVAULT_TMPDIR: ./tmp
  # Force UTF-8 support since we need that for safe tests around
  # roundtrip encoding.
  LANG: C.UTF-8
  LC_ALL: C.UTF-8
  LC_CTYPE: C.UTF-8

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:25.1.1

    steps:
    - uses: actions/checkout@v3
    - name: Run validation checks
      run: rebar3 check
    - name: Release can be built
      run: rebar3 do release, tar
    - name: CLI tool can be built
      run: rebar3 as prod escriptize

